### ISSUE TITLE
Unknown permission denied error

### ISSUE THREAD

**Issue by IlexisTheMadcat** [SUPERMECHM500/MWSRam#17]
![image](https://user-images.githubusercontent.com/50256109/84176801-96f10800-aa47-11ea-950f-ad5c8c3bbf60.png)

**Comment by IlexisTheMadcat** [comment]
Possibly occurred while auto-pulling.
Caused Ram to send me a DM
![image](https://user-images.githubusercontent.com/50256109/84177646-bf2d3680-aa48-11ea-821c-8352a55e9b94.png)

**Comment by SirThane** [comment]
Has this error occurred since moving the repos out of OneDrive-synced directories? If so, that's more evidence supporting the plausible explanation that aspects of OneDrive synchronization is interfering with Git. The behavior displayed in the image does not appear to be the same as the error sent to console. If it is no longer occurring, I'd call this resolved.

**Comment by IlexisTheMadcat** [comment]
It doesn't appear that Ram received this error in the full time of running since 09:00 CST
